from django.db import models
from conexoes.models import MkPessoas

# Create your models here.
class MkBoletosGerados(models.Model):
    codgeracao = models.AutoField(primary_key=True)
    valor = models.FloatField(blank=True, null=True)
    vencimento = models.CharField(max_length=30, blank=True, null=True)
    nosso_numero = models.CharField(max_length=20, blank=True, null=True)
    nome_sacado = models.CharField(max_length=100, blank=True, null=True)
    endereco = models.CharField(max_length=200, blank=True, null=True)
    cep = models.CharField(max_length=8, blank=True, null=True)
    cidade = models.CharField(max_length=50, blank=True, null=True)
    estado = models.CharField(max_length=3, blank=True, null=True)
    linha1 = models.CharField(max_length=200, blank=True, null=True)
    linha2 = models.CharField(max_length=200, blank=True, null=True)
    linha3 = models.CharField(max_length=200, blank=True, null=True)
    linha4 = models.CharField(max_length=200, blank=True, null=True)
    linha5 = models.CharField(max_length=200, blank=True, null=True)
    linha6 = models.CharField(max_length=200, blank=True, null=True)
    linha7 = models.CharField(max_length=200, blank=True, null=True)
    linha8 = models.CharField(max_length=200, blank=True, null=True)
    nome_cedente = models.CharField(max_length=100, blank=True, null=True)
    local_pgto = models.CharField(max_length=200, blank=True, null=True)
    tx_aux_1 = models.CharField(max_length=200, blank=True, null=True)
    tx_aux_2 = models.CharField(max_length=200, blank=True, null=True)
    tx_aux_3 = models.CharField(max_length=200, blank=True, null=True)
    tx_aux_4 = models.CharField(max_length=200, blank=True, null=True)
    tx_aux_5 = models.CharField(max_length=200, blank=True, null=True)
    tx_aux_6 = models.CharField(max_length=200, blank=True, null=True)
    tx_aux_7 = models.CharField(max_length=200, blank=True, null=True)
    banco = models.CharField(max_length=20, blank=True, null=True)
    agencia = models.CharField(max_length=20, blank=True, null=True)
    aceite = models.CharField(max_length=10, blank=True, null=True)
    cedente_barra = models.CharField(max_length=50, blank=True, null=True)
    cod_cliente = models.CharField(max_length=20, blank=True, null=True)
    cnpj_cedente = models.CharField(max_length=20, blank=True, null=True)
    cpf_cnpj_sacado = models.CharField(max_length=20, blank=True, null=True)
    data_processamento = models.CharField(max_length=30, blank=True, null=True)
    desconto = models.CharField(max_length=10, blank=True, null=True)
    modalidade = models.CharField(max_length=50, blank=True, null=True)
    multa = models.CharField(max_length=10, blank=True, null=True)
    num_convenio = models.CharField(max_length=30, blank=True, null=True)
    num_doc = models.CharField(max_length=30, blank=True, null=True)
    parcela = models.CharField(max_length=10, blank=True, null=True)
    carteira = models.CharField(max_length=10, blank=True, null=True)
    cod_cedente = models.CharField(max_length=15, blank=True, null=True)
    outros_acrescimos = models.CharField(max_length=10, blank=True, null=True)
    valor_cobrado = models.CharField(max_length=100, blank=True, null=True)
    codconta = models.IntegerField(blank=True, null=True)
   # profile = models.ForeignKey('MkProfilePgto', models.DO_NOTHING, db_column='profile', blank=True, null=True)
    substituido = models.CharField(max_length=1, blank=True, null=True)
    data_remocao = models.DateField(blank=True, null=True)
    hora_remocao = models.CharField(max_length=10, blank=True, null=True)
    user_remocao = models.CharField(max_length=50, blank=True, null=True)
    codcontrato = models.IntegerField(blank=True, null=True)
    tx_mens_titulo = models.CharField(max_length=200, blank=True, null=True)
    tx_mens_linha1 = models.CharField(max_length=200, blank=True, null=True)
    tx_mens_linha2 = models.CharField(max_length=200, blank=True, null=True)
    tx_mens_linha3 = models.CharField(max_length=200, blank=True, null=True)
    tx_mens_linha4 = models.CharField(max_length=200, blank=True, null=True)
    tx_mens_linha5 = models.CharField(max_length=200, blank=True, null=True)
    tx_mens_linha6 = models.CharField(max_length=200, blank=True, null=True)
    tx_mens_linha7 = models.CharField(max_length=200, blank=True, null=True)
    smtp = models.CharField(max_length=100, blank=True, null=True)
    username = models.CharField(max_length=100, blank=True, null=True)
    password = models.CharField(max_length=50, blank=True, null=True)
    email_origem = models.CharField(max_length=100, blank=True, null=True)
    email_destino = models.CharField(max_length=100, blank=True, null=True)
    conta_email = models.IntegerField(blank=True, null=True)
    vencimento_dt_normal = models.DateField(blank=True, null=True)
    guid = models.CharField(max_length=50, blank=True, null=True)
    arquivo_remessa = models.CharField(max_length=1, blank=True, null=True)
    gerado_transmissao = models.CharField(max_length=1, blank=True, null=True)
    dt_ger_transmissao = models.DateField(blank=True, null=True)
    tmp_trans = models.CharField(max_length=1, blank=True, null=True)
    nome_arquivo = models.CharField(max_length=50, blank=True, null=True)
    seq_arq_remessa = models.IntegerField(blank=True, null=True)
    tmp_marca_consulta = models.CharField(max_length=1, blank=True, null=True)
    guid_envio_email = models.CharField(max_length=50, blank=True, null=True)
    ret_nosso_num_banco = models.CharField(max_length=20, blank=True, null=True)
    profile_antiga = models.IntegerField(blank=True, null=True)
    entrada_confirmada = models.CharField(max_length=1, blank=True, null=True)
    nomenclatura_integracao = models.CharField(max_length=3, blank=True, null=True)
    codvinculado = models.IntegerField(blank=True, null=True)
    nosso_numero2 = models.CharField(max_length=20, blank=True, null=True)
    guid_exibicao = models.CharField(max_length=50, blank=True, null=True)
    suspenso = models.CharField(max_length=1, blank=True, null=True)
    cd_fatura = models.OneToOneField('MkFaturas', models.DO_NOTHING, db_column='cd_fatura', blank=True, null=True)
    profile_redefinida = models.CharField(max_length=1, blank=True, null=True)
    profile_original = models.IntegerField(blank=True, null=True)
    codigo_barras = models.CharField(unique=True, max_length=100, blank=True, null=True)
    linha_digitavel = models.CharField(unique=True, max_length=100, blank=True, null=True)
    nosso_numero_formatado = models.CharField(max_length=50, blank=True, null=True)
    hash_integridade = models.CharField(max_length=50, blank=True, null=True)
    instrucoes = models.TextField(blank=True, null=True)
    id_unificacao = models.IntegerField(blank=True, null=True)
    cd_boleto_replicado = models.IntegerField(blank=True, null=True)
    cd_empresa = models.IntegerField(blank=True, null=True)
    tmp_trans_em_pendencia = models.CharField(max_length=1, blank=True, null=True)
    guid_controle_back = models.CharField(max_length=50, blank=True, null=True)
    nome_file_back = models.CharField(max_length=50, blank=True, null=True)
    controle_de_ordenacao = models.IntegerField(blank=True, null=True)
    nosso_numero_dv = models.CharField(max_length=2, blank=True, null=True)
    guid_controle_troca_profile = models.CharField(max_length=50, blank=True, null=True)
    dh = models.DateTimeField(blank=True, null=True)
    cd_remessa_gerada = models.IntegerField(blank=True, null=True)
    parcela_i_carne = models.IntegerField(blank=True, null=True)
    parcela_f_carne = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'mk_boletos_gerados'
       # unique_together = (('nosso_numero_formatado', 'profile'), ('nosso_numero', 'id_unificacao'), ('nosso_numero', 'profile'),)


class MkFaturas(models.Model):
    codfatura = models.AutoField(primary_key=True)
    data_lancamento = models.DateTimeField(blank=True, null=True)
    usuario_lancamento = models.CharField(max_length=100, blank=True, null=True)
    valor_total = models.FloatField(blank=True, null=True)
    data_vencimento = models.DateField(blank=True, null=True)
    excluida = models.CharField(max_length=1, blank=True, null=True)
    usuario_exclusao = models.CharField(max_length=100, blank=True, null=True)
    data_exclusao = models.DateTimeField(blank=True, null=True)
    cd_pessoa = models.ForeignKey(MkPessoas, models.DO_NOTHING, db_column='cd_pessoa', blank=True, null=True)
    tipo_lancamento = models.CharField(max_length=50, blank=True, null=True)
    liquidado = models.CharField(max_length=1, blank=True, null=True)
    data_liquidacao = models.DateField(blank=True, null=True)
    hora_liquidacao = models.CharField(max_length=8, blank=True, null=True)
    vlr_liquidacao = models.FloatField(blank=True, null=True)
    usuario_liquidacao = models.CharField(max_length=30, blank=True, null=True)
    hora_exclusao = models.CharField(max_length=8, blank=True, null=True)
    # cd_faturamento = models.ForeignKey(MkFatV2, models.DO_NOTHING, db_column='cd_faturamento', blank=True, null=True)
    guid_selecao = models.CharField(max_length=100, blank=True, null=True)
    tx_multa_atraso = models.FloatField(blank=True, null=True)
    tx_juro_atraso = models.FloatField(blank=True, null=True)
    dt_ref_inicial = models.DateField(blank=True, null=True)
    dt_ref_final = models.DateField(blank=True, null=True)
    descricao = models.CharField(max_length=250, blank=True, null=True)
    forma_pgto_liquidacao = models.IntegerField(blank=True, null=True)
    obs_liquidacao = models.TextField(blank=True, null=True)
    documento_liquidacao = models.CharField(max_length=20, blank=True, null=True)
    ponto_recebimento_liquidacao = models.IntegerField(blank=True, null=True)
    dt_efetivacao_credito = models.DateField(blank=True, null=True)
    vlr_acrescimo_aplicado = models.FloatField(blank=True, null=True)
    vlr_desconto_aplicado = models.FloatField(blank=True, null=True)
    vlr_tarifa_aplicada = models.FloatField(blank=True, null=True)
    desconto_maximo_aplicavel = models.FloatField(blank=True, null=True)
    data_desconto_maximo = models.DateField(blank=True, null=True)
    suspenso = models.CharField(max_length=1, blank=True, null=True)
    data_vencimento_original = models.DateField(blank=True, null=True)
    valor_total_original = models.FloatField(blank=True, null=True)
    num_reprogramacao = models.IntegerField(blank=True, null=True)
    info_reprogramacao = models.TextField(blank=True, null=True)
    cd_motivo_suspensao = models.IntegerField(blank=True, null=True)
    exportacao = models.CharField(max_length=1, blank=True, null=True)
    exportacao_data_hora = models.DateTimeField(blank=True, null=True)
    exportacao_arquivo = models.CharField(max_length=100, blank=True, null=True)
    agrupamento = models.CharField(max_length=30, blank=True, null=True)
    usuario_suspensao = models.CharField(max_length=100, blank=True, null=True)
    data_suspensao = models.DateTimeField(blank=True, null=True)
    obs_suspensao = models.TextField(blank=True, null=True)
    obs_fatura = models.TextField(blank=True, null=True)
    liquidado_por_retorno = models.CharField(max_length=1, blank=True, null=True)
    num_arq_retorno = models.IntegerField(blank=True, null=True)
    cd_empresa = models.IntegerField(blank=True, null=True)
    estornado = models.CharField(max_length=1, blank=True, null=True)
    data_estorno = models.DateField(blank=True, null=True)
    hora_estorno = models.CharField(max_length=8, blank=True, null=True)
    vlr_estorno = models.FloatField(blank=True, null=True)
    usuario_estorno = models.CharField(max_length=30, blank=True, null=True)
    tipo = models.CharField(max_length=1, blank=True, null=True)
    documento_cobranca = models.CharField(max_length=30, blank=True, null=True)
    dt_hr_evento_liquidacao = models.DateTimeField(blank=True, null=True)
    doc_fiscais_gerados = models.CharField(max_length=1, blank=True, null=True)
    nomenclatura_integracao = models.CharField(max_length=3, blank=True, null=True)
    cd_vinculado = models.IntegerField(blank=True, null=True)
    barras_cobranca = models.CharField(unique=True, max_length=100, blank=True, null=True)
    ld_cobranca = models.CharField(unique=True, max_length=100, blank=True, null=True)
    dh_geracao = models.DateTimeField(blank=True, null=True)
    id_operador = models.IntegerField(blank=True, null=True)
    tipo_cobranca = models.IntegerField(blank=True, null=True)
    dh_registro = models.DateTimeField(blank=True, null=True)
    numero_cobranca = models.CharField(max_length=20, blank=True, null=True)
    cd_profile_cobranca = models.IntegerField(blank=True, null=True)
    cd_doc_cobranca = models.IntegerField(blank=True, null=True)
    opcao_lcto = models.IntegerField(blank=True, null=True)
    # plano_contas = models.ForeignKey('MkUnidadeFinanceia', models.DO_NOTHING, db_column='plano_contas', blank=True, null=True)
    # cc_departamentos = models.ForeignKey(MkCcRateio, models.DO_NOTHING, db_column='cc_departamentos', blank=True, null=True)
    # cc_servicos = models.ForeignKey(MkCcRateio, models.DO_NOTHING, db_column='cc_servicos', blank=True, null=True)
    # cc_projetos = models.ForeignKey(MkCcRateio, models.DO_NOTHING, db_column='cc_projetos', blank=True, null=True)
    # cc_area_negocios = models.ForeignKey(MkCcRateio, models.DO_NOTHING, db_column='cc_area_negocios', blank=True, null=True)
    dh_insert = models.DateTimeField(blank=True, null=True)
    conta_fixa = models.CharField(max_length=1, blank=True, null=True)
    # cd_agrupador = models.ForeignKey(MkContratosAgrupadores, models.DO_NOTHING, db_column='cd_agrupador', blank=True, null=True)
    saldo_restante = models.DecimalField(max_digits=11, decimal_places=2, blank=True, null=True)
    valor_liquidado = models.DecimalField(max_digits=11, decimal_places=2, blank=True, null=True)
    ver_geracao_doc_fiscal = models.IntegerField(blank=True, null=True)
    teve_liquidacao_parcial = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'mk_faturas'