from django.db import models

# Create your models here.
class MkBoletosGerados(models.Model):
    codgeracao = models.AutoField(primary_key=True)
    valor = models.FloatField(blank=True, null=True)
    vencimento = models.CharField(max_length=30, blank=True, null=True)
    nosso_numero = models.CharField(max_length=20, blank=True, null=True)
    nome_sacado = models.CharField(max_length=100, blank=True, null=True)
    endereco = models.CharField(max_length=200, blank=True, null=True)
    cep = models.CharField(max_length=8, blank=True, null=True)
    cidade = models.CharField(max_length=50, blank=True, null=True)
    estado = models.CharField(max_length=3, blank=True, null=True)
    linha1 = models.CharField(max_length=200, blank=True, null=True)
    linha2 = models.CharField(max_length=200, blank=True, null=True)
    linha3 = models.CharField(max_length=200, blank=True, null=True)
    linha4 = models.CharField(max_length=200, blank=True, null=True)
    linha5 = models.CharField(max_length=200, blank=True, null=True)
    linha6 = models.CharField(max_length=200, blank=True, null=True)
    linha7 = models.CharField(max_length=200, blank=True, null=True)
    linha8 = models.CharField(max_length=200, blank=True, null=True)
    nome_cedente = models.CharField(max_length=100, blank=True, null=True)
    local_pgto = models.CharField(max_length=200, blank=True, null=True)
    tx_aux_1 = models.CharField(max_length=200, blank=True, null=True)
    tx_aux_2 = models.CharField(max_length=200, blank=True, null=True)
    tx_aux_3 = models.CharField(max_length=200, blank=True, null=True)
    tx_aux_4 = models.CharField(max_length=200, blank=True, null=True)
    tx_aux_5 = models.CharField(max_length=200, blank=True, null=True)
    tx_aux_6 = models.CharField(max_length=200, blank=True, null=True)
    tx_aux_7 = models.CharField(max_length=200, blank=True, null=True)
    banco = models.CharField(max_length=20, blank=True, null=True)
    agencia = models.CharField(max_length=20, blank=True, null=True)
    aceite = models.CharField(max_length=10, blank=True, null=True)
    cedente_barra = models.CharField(max_length=50, blank=True, null=True)
    cod_cliente = models.CharField(max_length=20, blank=True, null=True)
    cnpj_cedente = models.CharField(max_length=20, blank=True, null=True)
    cpf_cnpj_sacado = models.CharField(max_length=20, blank=True, null=True)
    data_processamento = models.CharField(max_length=30, blank=True, null=True)
    desconto = models.CharField(max_length=10, blank=True, null=True)
    modalidade = models.CharField(max_length=50, blank=True, null=True)
    multa = models.CharField(max_length=10, blank=True, null=True)
    num_convenio = models.CharField(max_length=30, blank=True, null=True)
    num_doc = models.CharField(max_length=30, blank=True, null=True)
    parcela = models.CharField(max_length=10, blank=True, null=True)
    carteira = models.CharField(max_length=10, blank=True, null=True)
    cod_cedente = models.CharField(max_length=15, blank=True, null=True)
    outros_acrescimos = models.CharField(max_length=10, blank=True, null=True)
    valor_cobrado = models.CharField(max_length=100, blank=True, null=True)
    codconta = models.IntegerField(blank=True, null=True)
   # profile = models.ForeignKey('MkProfilePgto', models.DO_NOTHING, db_column='profile', blank=True, null=True)
    substituido = models.CharField(max_length=1, blank=True, null=True)
    data_remocao = models.DateField(blank=True, null=True)
    hora_remocao = models.CharField(max_length=10, blank=True, null=True)
    user_remocao = models.CharField(max_length=50, blank=True, null=True)
    codcontrato = models.IntegerField(blank=True, null=True)
    tx_mens_titulo = models.CharField(max_length=200, blank=True, null=True)
    tx_mens_linha1 = models.CharField(max_length=200, blank=True, null=True)
    tx_mens_linha2 = models.CharField(max_length=200, blank=True, null=True)
    tx_mens_linha3 = models.CharField(max_length=200, blank=True, null=True)
    tx_mens_linha4 = models.CharField(max_length=200, blank=True, null=True)
    tx_mens_linha5 = models.CharField(max_length=200, blank=True, null=True)
    tx_mens_linha6 = models.CharField(max_length=200, blank=True, null=True)
    tx_mens_linha7 = models.CharField(max_length=200, blank=True, null=True)
    smtp = models.CharField(max_length=100, blank=True, null=True)
    username = models.CharField(max_length=100, blank=True, null=True)
    password = models.CharField(max_length=50, blank=True, null=True)
    email_origem = models.CharField(max_length=100, blank=True, null=True)
    email_destino = models.CharField(max_length=100, blank=True, null=True)
    conta_email = models.IntegerField(blank=True, null=True)
    vencimento_dt_normal = models.DateField(blank=True, null=True)
    guid = models.CharField(max_length=50, blank=True, null=True)
    arquivo_remessa = models.CharField(max_length=1, blank=True, null=True)
    gerado_transmissao = models.CharField(max_length=1, blank=True, null=True)
    dt_ger_transmissao = models.DateField(blank=True, null=True)
    tmp_trans = models.CharField(max_length=1, blank=True, null=True)
    nome_arquivo = models.CharField(max_length=50, blank=True, null=True)
    seq_arq_remessa = models.IntegerField(blank=True, null=True)
    tmp_marca_consulta = models.CharField(max_length=1, blank=True, null=True)
    guid_envio_email = models.CharField(max_length=50, blank=True, null=True)
    ret_nosso_num_banco = models.CharField(max_length=20, blank=True, null=True)
    profile_antiga = models.IntegerField(blank=True, null=True)
    entrada_confirmada = models.CharField(max_length=1, blank=True, null=True)
    nomenclatura_integracao = models.CharField(max_length=3, blank=True, null=True)
    codvinculado = models.IntegerField(blank=True, null=True)
    nosso_numero2 = models.CharField(max_length=20, blank=True, null=True)
    guid_exibicao = models.CharField(max_length=50, blank=True, null=True)
    suspenso = models.CharField(max_length=1, blank=True, null=True)
   # cd_fatura = models.OneToOneField('MkFaturas', models.DO_NOTHING, db_column='cd_fatura', blank=True, null=True)
    profile_redefinida = models.CharField(max_length=1, blank=True, null=True)
    profile_original = models.IntegerField(blank=True, null=True)
    codigo_barras = models.CharField(unique=True, max_length=100, blank=True, null=True)
    linha_digitavel = models.CharField(unique=True, max_length=100, blank=True, null=True)
    nosso_numero_formatado = models.CharField(max_length=50, blank=True, null=True)
    hash_integridade = models.CharField(max_length=50, blank=True, null=True)
    instrucoes = models.TextField(blank=True, null=True)
    id_unificacao = models.IntegerField(blank=True, null=True)
    cd_boleto_replicado = models.IntegerField(blank=True, null=True)
    cd_empresa = models.IntegerField(blank=True, null=True)
    tmp_trans_em_pendencia = models.CharField(max_length=1, blank=True, null=True)
    guid_controle_back = models.CharField(max_length=50, blank=True, null=True)
    nome_file_back = models.CharField(max_length=50, blank=True, null=True)
    controle_de_ordenacao = models.IntegerField(blank=True, null=True)
    nosso_numero_dv = models.CharField(max_length=2, blank=True, null=True)
    guid_controle_troca_profile = models.CharField(max_length=50, blank=True, null=True)
    dh = models.DateTimeField(blank=True, null=True)
    cd_remessa_gerada = models.IntegerField(blank=True, null=True)
    parcela_i_carne = models.IntegerField(blank=True, null=True)
    parcela_f_carne = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'mk_boletos_gerados'
       # unique_together = (('nosso_numero_formatado', 'profile'), ('nosso_numero', 'id_unificacao'), ('nosso_numero', 'profile'),)
